#!/usr/bin/env python

import argparse
import datetime
from importlib import import_module
from pathlib import Path
import shutil
import subprocess
import sys

DOCS_DIR = Path(sys.argv[0]).absolute().parent
MODULES_DIR = DOCS_DIR.parent.parent.parent
TKET_WEBSITE_LINK = "https://tket.quantinuum.com/"
PYTKET_DOCS_LINK = "https://tket.quantinuum.com/api-docs/"
PYTKET_EX_DOCS_LINK = "https://cqcl.github.io/pytket-extensions/api/index.html"
QUJAX_LINK = "https://cqcl.github.io/qujax/api/"
MODULE = "qujax"
GITHUB_LINK = "https://github.com/CQCL/pytket-qujax"
PYPI_LINK = "https://pypi.org/project/pytket-qujax/"
NOTEBOOK_LINK_1 = "https://github.com/CQCL/pytket/blob/main/examples/pytket-qujax_heisenberg_vqe.ipynb"
NOTEBOOK_LINK_2 = "https://github.com/CQCL/pytket/blob/main/examples/pytket-qujax_qaoa.ipynb"
NOTEBOOK_LINK_3 = "https://github.com/CQCL/pytket/blob/main/examples/pytket-qujax-classification.ipynb"
NOTEBOOK_LINK_QUJAX = "https://github.com/CQCL/qujax/tree/main/examples"


def get_module_version():
    m = import_module(f"pytket.extensions.{MODULE}")
    return m._metadata.__extension_version__.split(".")


def remove_dir(dirpath):
    if dirpath.exists() and dirpath.is_dir():
        shutil.rmtree(dirpath)


def fix_links(filepath):
    with open(filepath, "r", encoding="utf8") as f:
        content = f.read()
    content = content.replace("pytket.extensions.qujax.qujax_convert", "pytket.extensions.qujax")
    with open(filepath, "w", encoding="utf8") as f:
        f.write(content)


def build_module_docs():
    v = get_module_version()
    mod_docs = MODULES_DIR / "docs"
    mod_build = mod_docs / "build"
    conf_copy = mod_docs / "conf.py"
    logo_copy_black = mod_docs / "Quantinuum_logo_black.png"
    logo_copy_white = mod_docs / "Quantinuum_logo_white.png"
    shutil.copy(DOCS_DIR / "conf.py", conf_copy)
    shutil.copy(DOCS_DIR / "Quantinuum_logo_black.png", logo_copy_black)
    shutil.copy(DOCS_DIR / "Quantinuum_logo_white.png", logo_copy_white)
    remove_dir(mod_build)
    index_rst = mod_docs / "index.rst"
    with open(mod_docs / "intro.txt", "r") as f:
        content = f.readlines()
        content.append(
            "\n.. toctree::\n\t:caption: More documentation:\n\t:maxdepth: 1\n\n"
        )
        content.append(f"\tTKET website <{TKET_WEBSITE_LINK}>\n")
        content.append(f"\tpytket <{PYTKET_DOCS_LINK}>\n")
        content.append(f"\tpytket extensions <{PYTKET_EX_DOCS_LINK}>\n")
        content.append(f"\tqujax <{QUJAX_LINK}>\n")

        content.append(
            "\n.. toctree::\n\t:caption: Links:\n\t:maxdepth: 1\n\n"
        )
        content.append(f"\tGitHub <{GITHUB_LINK}>\n")
        content.append(f"\tPyPI <{PYPI_LINK}>\n")
        content.append(f"\tExample notebook (VQE) <{NOTEBOOK_LINK_1}>\n")
        content.append(f"\tExample notebook (QAOA with symbol_map) <{NOTEBOOK_LINK_2}>\n")
        content.append(f"\tExample notebook (classifier) <{NOTEBOOK_LINK_3}>\n")
        content.append(f"\t qujax example notebooks <{NOTEBOOK_LINK_QUJAX}>\n")

    with open(index_rst, "w") as f:
        f.writelines(content)
    subprocess.run(
        [
            "sphinx-build",
            "-b",
            "html",
            "-D",
            f"project=pytket-{MODULE}",
            "-D",
            f"copyright={datetime.date.today().year} Cambridge Quantum Computing",
            "-D",
            f"version={'.'.join(v)}",
            "-D",
            f"release={'.'.join(v)}",
            ".",
            "build",
        ],
        cwd=mod_docs,
    )
    for htmlfile in mod_build.rglob("*.html"):
        fix_links(htmlfile)
    fix_links(mod_build / "searchindex.js")
    conf_copy.unlink()
    logo_copy_black.unlink()
    logo_copy_white.unlink()
    index_rst.unlink()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build HTML documentation for pytket-qujax."
    )
    parser.add_argument("-d", "--dest", help="copy artifacts into destination folder")
    args = parser.parse_args()

    print("Building docs for modules:", MODULE)
    build_module_docs()

    if args.dest is not None:
        dest = Path(args.dest)
        shutil.copytree(
            MODULES_DIR / "docs" / "build",
            dest,
            dirs_exist_ok=True,
            )